[project]
name = "dotfiles"
version = "0.1.0"
description = "Personal dotfiles setup using Invoke and uv"
authors = [
  { name = "Eric Macedo" }
]
requires-python = ">=3.13"

dependencies = [
  "invoke>=2.2",
  "platformdirs>=4.0",
  "pyyaml>=6.0.3",
]

[tool.invoke]
namespace = "tasks"
