

PS1='${debian_chroot:+($debian_chroot)}\[\033[01;32m\]\u@\h\[\033[00m\]:\[\033[01;34m\]\w\[\033[00m\]\$ '

# User alias
alias lt="tree -L 1 -C --dirsfirst"

# tell perfoce which tool to use for diffs
export P4DIFF="nvim -d"
export PYTHONSTARTUP="/home/emacedo/.pythonrc.py"

eval "$(starship init bash)"
