# Enable history search with arrow keys
bindkey "^[[A" history-beginning-search-backward
bindkey "^[[B" history-beginning-search-forward

# User alias
# alias lt="tree -L 1 -C --dirsfirst"
alias edi-work="ssh emacedo@ediws1158 -t 'tmux new -As dev'"
alias aus-work="ssh emacedo@cadws1523 -t 'tmux new -As dev'"
alias lt="eza -l --tree --level 1 --classify=always --color=always --group-directories-first --no-permissions --no-user"

# Basic colorful prompt
PROMPT='%F{cyan}%n%f@%F{yellow}%m%f:%F{green}%~%f %# '
export PYTHONSTARTUP="/Users/emacedo/.pythonrc.py"
export PATH="/Users/emacedo/.local/bin:$PATH"

[ -f ~/.fzf.zsh ] && source ~/.fzf.zsh


# To customize prompt, run `p10k configure` or edit ~/.p10k.zsh.
eval "$(starship init zsh)"
